const champions = {
  266: {
    id: 266,
    key: 'aatrox',
    name: 'Aatrox',
    title: 'the Darkin Blade',
  },
  103: {
    id: 103,
    key: 'ahri',
    name: 'Ahri',
    title: 'the Nine-Tailed Fox',
  },
  84: {
    id: 84,
    key: 'akali',
    name: 'Akali',
    title: 'the Fist of Shadow',
  },
  12: {
    id: 12,
    key: 'alistar',
    name: 'Alistar',
    title: 'the Minotaur',
  },
  32: {
    id: 32,
    key: 'amumu',
    name: 'Amumu',
    title: 'the Sad Mummy',
  },
  34: {
    id: 34,
    key: 'anivia',
    name: 'Anivia',
    title: 'the Cryophoenix',
  },
  1: {
    id: 1,
    key: 'annie',
    name: 'Annie',
    title: 'the Dark Child',
  },
  22: {
    id: 22,
    key: 'ashe',
    name: 'Ashe',
    title: 'the Frost Archer',
  },
  136: {
    id: 136,
    key: 'aurelionsol',
    name: 'Aurelion Sol',
    title: 'The Star Forger',
  },
  268: {
    id: 268,
    key: 'azir',
    name: 'Azir',
    title: 'the Emperor of the Sands',
  },
  432: {
    id: 432,
    key: 'bard',
    name: 'Bard',
    title: 'the Wandering Caretaker',
  },
  53: {
    id: 53,
    key: 'blitzcrank',
    name: 'Blitzcrank',
    title: 'the Great Steam Golem',
  },
  63: {
    id: 63,
    key: 'brand',
    name: 'Brand',
    title: 'the Burning Vengeance',
  },
  201: {
    id: 201,
    key: 'braum',
    name: 'Braum',
    title: 'the Heart of the Freljord',
  },
  51: {
    id: 51,
    key: 'caitlyn',
    name: 'Caitlyn',
    title: 'the Sheriff of Piltover',
  },
  164: {
    id: 164,
    key: 'camille',
    name: 'Camille',
    title: 'the Steel Shadow',
  },
  69: {
    id: 69,
    key: 'cassiopeia',
    name: 'Cassiopeia',
    title: 'the Serpent\'s Embrace',
  },
  31: {
    id: 31,
    key: 'chogath',
    name: 'Cho\'Gath',
    title: 'the Terror of the Void',
  },
  42: {
    id: 42,
    key: 'corki',
    name: 'Corki',
    title: 'the Daring Bombardier',
  },
  122: {
    id: 122,
    key: 'darius',
    name: 'Darius',
    title: 'the Hand of Noxus',
  },
  131: {
    id: 131,
    key: 'diana',
    name: 'Diana',
    title: 'Scorn of the Moon',
  },
  119: {
    id: 119,
    key: 'draven',
    name: 'Draven',
    title: 'the Glorious Executioner',
  },
  36: {
    id: 36,
    key: 'drmundo',
    name: 'Dr. Mundo',
    title: 'the Madman of Zaun',
  },
  245: {
    id: 245,
    key: 'ekko',
    name: 'Ekko',
    title: 'the Boy Who Shattered Time',
  },
  60: {
    id: 60,
    key: 'elise',
    name: 'Elise',
    title: 'the Spider Queen',
  },
  28: {
    id: 28,
    key: 'evelynn',
    name: 'Evelynn',
    title: 'Agony\'s Embrace',
  },
  81: {
    id: 81,
    key: 'ezreal',
    name: 'Ezreal',
    title: 'the Prodigal Explorer',
  },
  9: {
    id: 9,
    key: 'fiddlesticks',
    name: 'Fiddlesticks',
    title: 'the Harbinger of Doom',
  },
  114: {
    id: 114,
    key: 'fiora',
    name: 'Fiora',
    title: 'the Grand Duelist',
  },
  105: {
    id: 105,
    key: 'fizz',
    name: 'Fizz',
    title: 'the Tidal Trickster',
  },
  3: {
    id: 3,
    key: 'galio',
    name: 'Galio',
    title: 'the Colossus',
  },
  41: {
    id: 41,
    key: 'gangplank',
    name: 'Gangplank',
    title: 'the Saltwater Scourge',
  },
  86: {
    id: 86,
    key: 'garen',
    name: 'Garen',
    title: 'The Might of Demacia',
  },
  150: {
    id: 150,
    key: 'gnar',
    name: 'Gnar',
    title: 'the Missing Link',
  },
  79: {
    id: 79,
    key: 'gragas',
    name: 'Gragas',
    title: 'the Rabble Rouser',
  },
  104: {
    id: 104,
    key: 'graves',
    name: 'Graves',
    title: 'the Outlaw',
  },
  120: {
    id: 120,
    key: 'hecarim',
    name: 'Hecarim',
    title: 'the Shadow of War',
  },
  74: {
    id: 74,
    key: 'heimerdinger',
    name: 'Heimerdinger',
    title: 'the Revered Inventor',
  },
  420: {
    id: 420,
    key: 'illaoi',
    name: 'Illaoi',
    title: 'the Kraken Priestess',
  },
  39: {
    id: 39,
    key: 'irelia',
    name: 'Irelia',
    title: 'the Will of the Blades',
  },
  427: {
    id: 427,
    key: 'ivern',
    name: 'Ivern',
    title: 'the Green Father',
  },
  40: {
    id: 40,
    key: 'janna',
    name: 'Janna',
    title: 'the Storm\'s Fury',
  },
  59: {
    id: 59,
    key: 'jarvaniv',
    name: 'Jarvan IV',
    title: 'the Exemplar of Demacia',
  },
  24: {
    id: 24,
    key: 'jax',
    name: 'Jax',
    title: 'Grandmaster at Arms',
  },
  126: {
    id: 126,
    key: 'jayce',
    name: 'Jayce',
    title: 'the Defender of Tomorrow',
  },
  202: {
    id: 202,
    key: 'jhin',
    name: 'Jhin',
    title: 'the Virtuoso',
  },
  222: {
    id: 222,
    key: 'jinx',
    name: 'Jinx',
    title: 'the Loose Cannon',
  },
  429: {
    id: 429,
    key: 'kalista',
    name: 'Kalista',
    title: 'the Spear of Vengeance',
  },
  43: {
    id: 43,
    key: 'karma',
    name: 'Karma',
    title: 'the Enlightened One',
  },
  30: {
    id: 30,
    key: 'karthus',
    name: 'Karthus',
    title: 'the Deathsinger',
  },
  38: {
    id: 38,
    key: 'kassadin',
    name: 'Kassadin',
    title: 'the Void Walker',
  },
  55: {
    id: 55,
    key: 'katarina',
    name: 'Katarina',
    title: 'the Sinister Blade',
  },
  10: {
    id: 10,
    key: 'kayle',
    name: 'Kayle',
    title: 'The Judicator',
  },
  141: {
    id: 141,
    key: 'kayn',
    name: 'Kayn',
    title: 'the Shadow Reaper',
  },
  85: {
    id: 85,
    key: 'kennen',
    name: 'Kennen',
    title: 'the Heart of the Tempest',
  },
  121: {
    id: 121,
    key: 'khazix',
    name: 'Kha\'Zix',
    title: 'the Voidreaver',
  },
  203: {
    id: 203,
    key: 'kindred',
    name: 'Kindred',
    title: 'The Eternal Hunters',
  },
  240: {
    id: 240,
    key: 'kled',
    name: 'Kled',
    title: 'the Cantankerous Cavalier',
  },
  96: {
    id: 96,
    key: 'kogmaw',
    name: 'Kog\'Maw',
    title: 'the Mouth of the Abyss',
  },
  7: {
    id: 7,
    key: 'leblanc',
    name: 'LeBlanc',
    title: 'the Deceiver',
  },
  64: {
    id: 64,
    key: 'leesin',
    name: 'Lee Sin',
    title: 'the Blind Monk',
  },
  89: {
    id: 89,
    key: 'leona',
    name: 'Leona',
    title: 'the Radiant Dawn',
  },
  127: {
    id: 127,
    key: 'lissandra',
    name: 'Lissandra',
    title: 'the Ice Witch',
  },
  236: {
    id: 236,
    key: 'lucian',
    name: 'Lucian',
    title: 'the Purifier',
  },
  117: {
    id: 117,
    key: 'lulu',
    name: 'Lulu',
    title: 'the Fae Sorceress',
  },
  99: {
    id: 99,
    key: 'lux',
    name: 'Lux',
    title: 'the Lady of Luminosity',
  },
  54: {
    id: 54,
    key: 'malphite',
    name: 'Malphite',
    title: 'Shard of the Monolith',
  },
  90: {
    id: 90,
    key: 'malzahar',
    name: 'Malzahar',
    title: 'the Prophet of the Void',
  },
  57: {
    id: 57,
    key: 'maokai',
    name: 'Maokai',
    title: 'the Twisted Treant',
  },
  11: {
    id: 11,
    key: 'masteryi',
    name: 'Master Yi',
    title: 'the Wuju Bladesman',
  },
  21: {
    id: 21,
    key: 'missfortune',
    name: 'Miss Fortune',
    title: 'the Bounty Hunter',
  },
  62: {
    id: 62,
    key: 'monkeyking',
    name: 'Wukong',
    title: 'the Monkey King',
  },
  82: {
    id: 82,
    key: 'mordekaiser',
    name: 'Mordekaiser',
    title: 'the Iron Revenant',
  },
  25: {
    id: 25,
    key: 'morgana',
    name: 'Morgana',
    title: 'Fallen Angel',
  },
  267: {
    id: 267,
    key: 'nami',
    name: 'Nami',
    title: 'the Tidecaller',
  },
  75: {
    id: 75,
    key: 'nasus',
    name: 'Nasus',
    title: 'the Curator of the Sands',
  },
  111: {
    id: 111,
    key: 'nautilus',
    name: 'Nautilus',
    title: 'the Titan of the Depths',
  },
  76: {
    id: 76,
    key: 'nidalee',
    name: 'Nidalee',
    title: 'the Bestial Huntress',
  },
  56: {
    id: 56,
    key: 'nocturne',
    name: 'Nocturne',
    title: 'the Eternal Nightmare',
  },
  20: {
    id: 20,
    key: 'nunu',
    name: 'Nunu',
    title: 'the Yeti Rider',
  },
  2: {
    id: 2,
    key: 'olaf',
    name: 'Olaf',
    title: 'the Berserker',
  },
  61: {
    id: 61,
    key: 'orianna',
    name: 'Orianna',
    title: 'the Lady of Clockwork',
  },
  516: {
    id: 516,
    key: 'ornn',
    name: 'Ornn',
    title: 'The Fire below the Mountain',
  },
  80: {
    id: 80,
    key: 'pantheon',
    name: 'Pantheon',
    title: 'the Artisan of War',
  },
  78: {
    id: 78,
    key: 'poppy',
    name: 'Poppy',
    title: 'Keeper of the Hammer',
  },
  133: {
    id: 133,
    key: 'quinn',
    name: 'Quinn',
    title: 'Demacia\'s Wings',
  },
  497: {
    id: 497,
    key: 'rakan',
    name: 'Rakan',
    title: 'The Charmer',
  },
  33: {
    id: 33,
    key: 'rammus',
    name: 'Rammus',
    title: 'the Armordillo',
  },
  421: {
    id: 421,
    key: 'reksai',
    name: 'Rek\'Sai',
    title: 'the Void Burrower',
  },
  58: {
    id: 58,
    key: 'renekton',
    name: 'Renekton',
    title: 'the Butcher of the Sands',
  },
  107: {
    id: 107,
    key: 'rengar',
    name: 'Rengar',
    title: 'the Pridestalker',
  },
  92: {
    id: 92,
    key: 'riven',
    name: 'Riven',
    title: 'the Exile',
  },
  68: {
    id: 68,
    key: 'rumble',
    name: 'Rumble',
    title: 'the Mechanized Menace',
  },
  13: {
    id: 13,
    key: 'ryze',
    name: 'Ryze',
    title: 'the Rune Mage',
  },
  113: {
    id: 113,
    key: 'sejuani',
    name: 'Sejuani',
    title: 'Fury of the North',
  },
  35: {
    id: 35,
    key: 'shaco',
    name: 'Shaco',
    title: 'the Demon Jester',
  },
  98: {
    id: 98,
    key: 'shen',
    name: 'Shen',
    title: 'the Eye of Twilight',
  },
  102: {
    id: 102,
    key: 'shyvana',
    name: 'Shyvana',
    title: 'the Half-Dragon',
  },
  27: {
    id: 27,
    key: 'singed',
    name: 'Singed',
    title: 'the Mad Chemist',
  },
  14: {
    id: 14,
    key: 'sion',
    name: 'Sion',
    title: 'The Undead Juggernaut',
  },
  15: {
    id: 15,
    key: 'sivir',
    name: 'Sivir',
    title: 'the Battle Mistress',
  },
  72: {
    id: 72,
    key: 'skarner',
    name: 'Skarner',
    title: 'the Crystal Vanguard',
  },
  37: {
    id: 37,
    key: 'sona',
    name: 'Sona',
    title: 'Maven of the Strings',
  },
  16: {
    id: 16,
    key: 'soraka',
    name: 'Soraka',
    title: 'the Starchild',
  },
  50: {
    id: 50,
    key: 'swain',
    name: 'Swain',
    title: 'the Master Tactician',
  },
  134: {
    id: 134,
    key: 'syndra',
    name: 'Syndra',
    title: 'the Dark Sovereign',
  },
  223: {
    id: 223,
    key: 'tahmkench',
    name: 'Tahm Kench',
    title: 'the River King',
  },
  163: {
    id: 163,
    key: 'taliyah',
    name: 'Taliyah',
    title: 'the Stoneweaver',
  },
  91: {
    id: 91,
    key: 'talon',
    name: 'Talon',
    title: 'the Blade\'s Shadow',
  },
  44: {
    id: 44,
    key: 'taric',
    name: 'Taric',
    title: 'the Shield of Valoran',
  },
  17: {
    id: 17,
    key: 'teemo',
    name: 'Teemo',
    title: 'the Swift Scout',
  },
  412: {
    id: 412,
    key: 'thresh',
    name: 'Thresh',
    title: 'the Chain Warden',
  },
  18: {
    id: 18,
    key: 'tristana',
    name: 'Tristana',
    title: 'the Yordle Gunner',
  },
  48: {
    id: 48,
    key: 'trundle',
    name: 'Trundle',
    title: 'the Troll King',
  },
  23: {
    id: 23,
    key: 'tryndamere',
    name: 'Tryndamere',
    title: 'the Barbarian King',
  },
  4: {
    id: 4,
    key: 'twistedfate',
    name: 'Twisted Fate',
    title: 'the Card Master',
  },
  29: {
    id: 29,
    key: 'twitch',
    name: 'Twitch',
    title: 'the Plague Rat',
  },
  77: {
    id: 77,
    key: 'udyr',
    name: 'Udyr',
    title: 'the Spirit Walker',
  },
  6: {
    id: 6,
    key: 'urgot',
    name: 'Urgot',
    title: 'the Dreadnought',
  },
  110: {
    id: 110,
    key: 'varus',
    name: 'Varus',
    title: 'the Arrow of Retribution',
  },
  67: {
    id: 67,
    key: 'vayne',
    name: 'Vayne',
    title: 'the Night Hunter',
  },
  45: {
    id: 45,
    key: 'veigar',
    name: 'Veigar',
    title: 'the Tiny Master of Evil',
  },
  161: {
    id: 161,
    key: 'velkoz',
    name: 'Vel\'Koz',
    title: 'the Eye of the Void',
  },
  254: {
    id: 254,
    key: 'vi',
    name: 'Vi',
    title: 'the Piltover Enforcer',
  },
  112: {
    id: 112,
    key: 'viktor',
    name: 'Viktor',
    title: 'the Machine Herald',
  },
  8: {
    id: 8,
    key: 'vladimir',
    name: 'Vladimir',
    title: 'the Crimson Reaper',
  },
  106: {
    id: 106,
    key: 'volibear',
    name: 'Volibear',
    title: 'the Thunder\'s Roar',
  },
  19: {
    id: 19,
    key: 'warwick',
    name: 'Warwick',
    title: 'the Uncaged Wrath of Zaun',
  },
  498: {
    id: 498,
    key: 'xayah',
    name: 'Xayah',
    title: 'the Rebel',
  },
  101: {
    id: 101,
    key: 'xerath',
    name: 'Xerath',
    title: 'the Magus Ascendant',
  },
  5: {
    id: 5,
    key: 'xinzhao',
    name: 'Xin Zhao',
    title: 'the Seneschal of Demacia',
  },
  157: {
    id: 157,
    key: 'yasuo',
    name: 'Yasuo',
    title: 'the Unforgiven',
  },
  83: {
    id: 83,
    key: 'yorick',
    name: 'Yorick',
    title: 'Shepherd of Souls',
  },
  154: {
    id: 154,
    key: 'zac',
    name: 'Zac',
    title: 'the Secret Weapon',
  },
  238: {
    id: 238,
    key: 'zed',
    name: 'Zed',
    title: 'the Master of Shadows',
  },
  115: {
    id: 115,
    key: 'ziggs',
    name: 'Ziggs',
    title: 'the Hexplosives Expert',
  },
  26: {
    id: 26,
    key: 'zilean',
    name: 'Zilean',
    title: 'the Chronokeeper',
  },
  142: {
    id: 142,
    key: 'zoe',
    name: 'Zoe',
    title: 'the Aspect of Twilight',
  },
  143: {
    id: 143,
    key: 'zyra',
    name: 'Zyra',
    title: 'Rise of the Thorns',
  },
}

export default champions